name: Test and Deploy
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Testing/requirements.txt

      - name: Install Playwright Browsers
        run: python -m playwright install

      - name: Run Test
        run: python ./Testing/testing.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Sync S3 Bucket
        run: aws s3 sync ./frontend s3://cloudresumechallenge-devarshtest --delete
